In [1]:
import numpy as np

In [2]:
input_feature_map = np.random.randint(0, 10, (3,56,56))
input_feature_map

array([[[0, 3, 8, ..., 6, 9, 3],
        [7, 3, 0, ..., 9, 7, 3],
        [2, 3, 1, ..., 5, 7, 0],
        ...,
        [9, 2, 2, ..., 9, 6, 8],
        [5, 9, 1, ..., 8, 8, 1],
        [8, 1, 6, ..., 5, 2, 9]],

       [[4, 8, 1, ..., 7, 2, 0],
        [5, 2, 3, ..., 9, 1, 5],
        [7, 3, 4, ..., 4, 1, 1],
        ...,
        [1, 6, 4, ..., 8, 3, 2],
        [4, 2, 3, ..., 5, 3, 3],
        [5, 2, 5, ..., 7, 3, 7]],

       [[9, 4, 5, ..., 3, 2, 6],
        [4, 6, 9, ..., 3, 6, 9],
        [1, 7, 9, ..., 8, 9, 6],
        ...,
        [1, 4, 6, ..., 5, 7, 8],
        [1, 7, 8, ..., 5, 3, 6],
        [3, 0, 0, ..., 7, 2, 7]]])

In [3]:
kernel = np.random.randint(0, 10, (3, 3, 3))
kernel

array([[[5, 8, 9],
        [2, 3, 5],
        [6, 3, 7]],

       [[8, 0, 8],
        [3, 3, 8],
        [9, 5, 9]],

       [[6, 2, 9],
        [6, 0, 2],
        [4, 5, 4]]])

In [4]:
input_feature_map.shape[1]

56

In [5]:
new_ifm = np.zeros(shape=(4, 4))
new_ifm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
def conv_element(mat, H, W, K, C):
    list_conv_element = []
    for i in range(H - K + 1):
        for j in range(W - K + 1):
            for c in range(C):
                for k1 in range(K):
                    for k2 in range(K):
                        list_conv_element.append(mat[c][i+k1][j+k2])
    return list_conv_element

conv_element(input_feature_map, 56, 56, 3, 3)

[0,
 3,
 8,
 7,
 3,
 0,
 2,
 3,
 1,
 4,
 8,
 1,
 5,
 2,
 3,
 7,
 3,
 4,
 9,
 4,
 5,
 4,
 6,
 9,
 1,
 7,
 9,
 3,
 8,
 4,
 3,
 0,
 3,
 3,
 1,
 4,
 8,
 1,
 3,
 2,
 3,
 9,
 3,
 4,
 2,
 4,
 5,
 0,
 6,
 9,
 8,
 7,
 9,
 6,
 8,
 4,
 1,
 0,
 3,
 1,
 1,
 4,
 5,
 1,
 3,
 5,
 3,
 9,
 0,
 4,
 2,
 0,
 5,
 0,
 5,
 9,
 8,
 6,
 9,
 6,
 9,
 4,
 1,
 5,
 3,
 1,
 1,
 4,
 5,
 6,
 3,
 5,
 2,
 9,
 0,
 3,
 2,
 0,
 7,
 0,
 5,
 3,
 8,
 6,
 2,
 6,
 9,
 9,
 1,
 5,
 9,
 1,
 1,
 6,
 5,
 6,
 4,
 5,
 2,
 9,
 0,
 3,
 2,
 0,
 7,
 4,
 5,
 3,
 6,
 6,
 2,
 2,
 9,
 9,
 9,
 5,
 9,
 5,
 1,
 6,
 8,
 6,
 4,
 0,
 2,
 9,
 4,
 3,
 2,
 9,
 7,
 4,
 1,
 3,
 6,
 3,
 2,
 2,
 3,
 9,
 9,
 4,
 9,
 5,
 7,
 6,
 8,
 7,
 4,
 0,
 8,
 9,
 4,
 4,
 2,
 9,
 5,
 4,
 1,
 2,
 6,
 3,
 3,
 2,
 3,
 0,
 9,
 4,
 5,
 5,
 7,
 5,
 8,
 7,
 4,
 0,
 8,
 9,
 4,
 4,
 2,
 9,
 5,
 6,
 1,
 2,
 2,
 3,
 3,
 3,
 3,
 0,
 0,
 4,
 5,
 1,
 7,
 5,
 3,
 7,
 4,
 0,
 8,
 9,
 9,
 4,
 2,
 5,
 5,
 6,
 3,
 2,
 2,
 4,
 3,
 3,
 1,
 0,
 0,
 0,
 5,
 1,
 0,
 5,
 3,
 1,
 4,
 0,
 8,
 9,


In [7]:
np.array(conv_element(input_feature_map, 56, 56, 3, 3)).reshape(-1,54)

array([[0, 3, 8, ..., 7, 9, 6],
       [8, 4, 1, ..., 6, 9, 9],
       [1, 5, 9, ..., 9, 9, 4],
       ...,
       [9, 5, 5, ..., 8, 5, 9],
       [5, 4, 7, ..., 9, 3, 7],
       [7, 9, 6, ..., 7, 2, 7]])

In [8]:
input_feature_map[0]

array([[0, 3, 8, ..., 6, 9, 3],
       [7, 3, 0, ..., 9, 7, 3],
       [2, 3, 1, ..., 5, 7, 0],
       ...,
       [9, 2, 2, ..., 9, 6, 8],
       [5, 9, 1, ..., 8, 8, 1],
       [8, 1, 6, ..., 5, 2, 9]])

In [9]:
list1 = conv_element(input_feature_map, 56, 56, 3, 3)

In [10]:
def img2col(mat, element_lsit, k_size=3, channel=3):
    """
    以img2col的方式展开矩阵. 只适用于stride为1
    """
    count = 0
    col_num = (mat.shape[1] - k_size + 1) * (mat.shape[2] - k_size + 1)
    row_num = k_size**2 * channel
    new_ifm = np.zeros(shape=(row_num, col_num))
    for j in range(col_num):
        for i in range(row_num):
            # i是新ifm的行标号， j是新ifm的列标号
            new_ifm[i][j] = element_lsit[count]
            count += 1
    return new_ifm

img2col(input_feature_map, list1)

array([[0., 3., 8., ..., 4., 7., 9.],
       [3., 8., 4., ..., 7., 9., 6.],
       [8., 4., 1., ..., 9., 6., 8.],
       ...,
       [1., 7., 9., ..., 9., 3., 7.],
       [7., 9., 6., ..., 3., 7., 2.],
       [9., 6., 9., ..., 7., 2., 7.]])

In [11]:
input_feature_map[0]

array([[0, 3, 8, ..., 6, 9, 3],
       [7, 3, 0, ..., 9, 7, 3],
       [2, 3, 1, ..., 5, 7, 0],
       ...,
       [9, 2, 2, ..., 9, 6, 8],
       [5, 9, 1, ..., 8, 8, 1],
       [8, 1, 6, ..., 5, 2, 9]])

In [12]:
input_feature_map[1]

array([[4, 8, 1, ..., 7, 2, 0],
       [5, 2, 3, ..., 9, 1, 5],
       [7, 3, 4, ..., 4, 1, 1],
       ...,
       [1, 6, 4, ..., 8, 3, 2],
       [4, 2, 3, ..., 5, 3, 3],
       [5, 2, 5, ..., 7, 3, 7]])

In [13]:
input_feature_map[2]

array([[9, 4, 5, ..., 3, 2, 6],
       [4, 6, 9, ..., 3, 6, 9],
       [1, 7, 9, ..., 8, 9, 6],
       ...,
       [1, 4, 6, ..., 5, 7, 8],
       [1, 7, 8, ..., 5, 3, 6],
       [3, 0, 0, ..., 7, 2, 7]])